# Dash LED PWM Example Makefile
# Copyright (c) 2015 Tony DiCola
# Released under a MIT license: http://opensource.org/licenses/MIT

BINARY = pwm

# Note if you have multiple source files, list them all in an OBJS variable.
# The Makefile rules will pick them up and compile their source appropriately.
# For example if you have a foo.c and bar.c to include set the OBJS variable:
# OBJS = foo.o bar.o

# Add to LDLIBS variable to add extra libraries at link time, like the math
# library with -lm.
LDLIBS += -lm

include ../Makefile.include
